### ISSUE TITLE
genToken错误，now 也错误

### ISSUE THREAD

**Issue by kalagxw** [JAVClub/proxy#3]
root@jav:~/JAVClub_proxy/vercel# node genToken,js
internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module '/root/JAVClub_proxy/vercel/genToken,js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND

=======now log======================================================
****
2020-08-09T16:08:19.607Z  installing dependencies for user's code...
2020-08-09T16:08:21.209Z  npm WARN vercel@1.0.0 No description
2020-08-09T16:08:21.209Z  npm WARN vercel@1.0.0 No repository field.
2020-08-09T16:08:21.209Z  
2020-08-09T16:08:21.210Z  added 73 packages from 56 contributors in 1.222s
2020-08-09T16:08:21.263Z  running user script...
2020-08-09T16:08:21.264Z  preparing lambda files...
2020-08-09T16:08:21.264Z  compiling entrypoint with ncc...
2020-08-09T16:08:21.481Z  ncc: Version 0.18.5
2020-08-09T16:08:21.481Z  ncc: Compiling file index.js
2020-08-09T16:08:23.347Z  ncc: Module directory "/vercel/7f959af9/node_modules/node-fetch/lib" attempted to require "encoding" but could not be resolved, assuming external.
2020-08-09T16:08:23.879Z  ncc: Module directory "/vercel/7f959af9/node_modules/https-proxy-agent/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
2020-08-09T16:08:23.911Z  ncc: Module directory "/vercel/7f959af9/node_modules/agent-base/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
2020-08-09T16:08:24.407Z  Error: Module not found: Error: Can't resolve './gdTokens' in '/vercel/7f959af9'
2020-08-09T16:08:24.407Z      at evalmachine.<anonymous>:3:1350338
2020-08-09T16:08:24.407Z      at eval (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:11:1)
2020-08-09T16:08:24.407Z      at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-09T16:08:24.576Z  
2020-08-09T16:08:25.263Z  
2020-08-09T16:08:26.251Z  Done with "app.js"
',
  requireStack: []
}

**Comment by znlnzi** [comment]
你写错了，是genToken.js 不是逗号,

**Comment by kalagxw** [comment]
该配眼镜了 -_-
